/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.app.view;

/**
 *
 * @author Thieu
 */
import com.mycompany.app.controller.StudentManagerController;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.mycompany.app.db.getDBconnection;
import com.mycompany.app.model.Department;
import com.mycompany.app.model.Student;
import com.mycompany.app.model.StudentResult;
import com.mycompany.app.model.StudentResults;
import com.mycompany.app.model.Subject;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import com.mycompany.app.view.addsvForm;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPopupMenu;
import javax.swing.JTable;

public class StudentManagementForm extends javax.swing.JFrame {

    /**
     * Creates new form qlsvForm
     */
     //public  StudentManagerController studentManagerController=StudentManagerController.getInstance();
    private addsvForm addForm;
    private Vector data = new Vector();
    private Vector column = new Vector();

    public StudentManagementForm() {
        initComponents();
        setLocationRelativeTo(null);
      //  addColumn();
       initializeData();
       

    }

    private void addColumn() {
         //  "CT0402000", "CT", "Thieu", 0, "Ha Noi", "CT4B", new Date());
        column.add("Mã SV");
        column.add("Tên SV");
        column.add("Giới tính");
        column.add("Quê quán");
        column.add("Lớp");
        column.add("Ngày sinh");
    }

    /**
     * Convert StudentResult to Vector, theo thu tu cac cot cua bien column
     *
     * @param studentResult
     * @return
     */
//    private Vector studentResultToVector(StudentResult studentResult) {
//        var v = new Vector();
//        v.add(studentResult.getStudent().getMaSV());
//        v.add(studentResult.getStudent().getTenSV());
//        v.add(studentResult.getStudent().getGioitinh());
//        v.add(studentResult.getStudent().getLop());
//        v.add(studentResult.getStudent().getTenSV());
//        v.add(studentResult.getStudent().getNgaysinh());
//        return v;
//    }

    private final StudentManagerController studentManagerController = StudentManagerController.getInstance();

    public void initializeData() {
        
        for(Department department:studentManagerController.getAllList())
        {
            
            jComboBoxDepartment.addItem(department.getName());
        }
        Department department=studentManagerController.getAllList().get(jComboBoxDepartment.getSelectedIndex());
        Subject subject=studentManagerController.subjectInDepartment(department).get(jComboBoxSubject.getSelectedIndex());
        System.out.println(department.getCode());
        List<StudentResult> list = studentManagerController.getStudentResultBySubjectAndDepartment("CT", subject.getCode());
         
         //StudentManagerController controler=StudentManagerController.getInstance();
         //ArrayList<StudentResults> list=controler.getAllResult();
//       Vector cols=new Vector();
//       
//       cols.add("Mã SV");
//       cols.add("Họ tên");
//       cols.add("Lớp");
//       cols.add("Điểm thành phần 1");
//       cols.add("Điểm thành phần 2");
//       cols.add("Điểm thi");
//       Vector rows=new Vector<>();
//       for(StudentResult result:list)
//       {
//           int i=0;
//           Vector  row=new Vector<>();
//           row.add(result.getStudent().getCode());
//           row.add(result.getStudent().getName());
//           row.add(result.getStudent().getKlass());
//           row.add(result.getResult().getPoint1());
//            row.add(result.getResult().getPoint2());
//             row.add(result.getResult().getPoint3());
//             i++;
//             rows.add(row);
//       }
//       tableSV.setModel(new DefaultTableModel(rows,cols)); 
    

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        bNew = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        bEdit = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        bDelete = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSV = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBoxDepartment = new javax.swing.JComboBox<>();
        jComboBoxSubject = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenuItem();
        menuQuit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hệ thống quản lý sinh viên");

        jToolBar1.setRollover(true);

        bNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new-icon-16.png"))); // NOI18N
        bNew.setText("Tạo mới");
        bNew.setFocusable(false);
        bNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNewActionPerformed(evt);
            }
        });
        jToolBar1.add(bNew);
        jToolBar1.add(jSeparator1);

        bEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Actions-document-edit-icon-16.png"))); // NOI18N
        bEdit.setText("Sửa thông tin");
        bEdit.setFocusable(false);
        bEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(bEdit);
        jToolBar1.add(jSeparator2);

        bDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Actions-edit-delete-icon-16.png"))); // NOI18N
        bDelete.setText("Xóa sinh viên");
        bDelete.setFocusable(false);
        bDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });
        jToolBar1.add(bDelete);
        jToolBar1.add(jSeparator3);

        tableSV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableSVMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableSV);

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-find-user-male-32.png"))); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Filter and Sort.png"))); // NOI18N
        jButton1.setText("Sắp xếp");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBoxDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDepartmentActionPerformed(evt);
            }
        });

        jComboBoxSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSubjectActionPerformed(evt);
            }
        });

        jButton2.setText("Xem kết quả thi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Xem thông tin sinh viên");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jMenu1.setText("Hệ thống");

        menuLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout-icon-16.png"))); // NOI18N
        menuLogout.setText("Đăng xuất");
        jMenu1.add(menuLogout);

        menuQuit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Button-Close-icon-16.png"))); // NOI18N
        menuQuit.setText("Thoát");
        jMenu1.add(menuQuit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jButton3)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNewActionPerformed
        // TODO add your handling code here:
        addForm = new addsvForm();
        addForm.setVisible(true);
    }//GEN-LAST:event_bNewActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bDeleteActionPerformed

    private void jComboBoxDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDepartmentActionPerformed
        // TODO add your handling code here:
        jComboBoxSubject.removeAllItems();
      List<Subject> list= 
              studentManagerController.subjectInDepartment(studentManagerController.getAllList().get(
                jComboBoxDepartment.getSelectedIndex()));
        for(Subject subject:list)
        {
            jComboBoxSubject.addItem(subject.getName());
        }
        
        
        
        
    }//GEN-LAST:event_jComboBoxDepartmentActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
//          Vector cols=new Vector();
//        cols.add("Tên Hàng");
//        cols.add("Số lượng");
//        cols.add("Đơn giá");
//        XuLiFile xl=new XuLiFile();
//        dsHH=xl.readFile("d:Hanghoa.dat");
//        Vector rows=new Vector<>();
//        for (HangHoa hh:dsHH) {
//            Vector  row=new Vector<>();
//            row.add(hh.getTen());
//            row.add(hh.getSoLuong());
//            row.add(hh.getDonGia());
//          rows.add(row);
//        }
//        table.setModel(new DefaultTableModel(rows,cols));
        StudentManagerController controler=StudentManagerController.getInstance();
         ArrayList<StudentResults> list=controler.getAllResult();
       Vector cols=new Vector();
       
       cols.add("Mã SV");
       cols.add("Họ tên");
       cols.add("Lớp");
       cols.add("Điểm thành phần 1");
       cols.add("Điểm thành phần 2");
       cols.add("Điểm thi");
       Vector rows=new Vector<>();
       for(StudentResults result:list)
       {
           int i=0;
           Vector  row=new Vector<>();
           row.add(result.getStudent().getCode());
           row.add(result.getStudent().getName());
           row.add(result.getStudent().getKlass());
           row.add(result.getResultList().get(i).getPoint1());
            row.add(result.getResultList().get(i).getPoint2());
             row.add(result.getResultList().get(i).getPoint3());
            
             i++;
             rows.add(row);
       }
         tableSV.setModel(new DefaultTableModel(rows,cols)); 
         
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tableSVMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSVMouseReleased
        // TODO add your handling code here:
         int r = tableSV.rowAtPoint(evt.getPoint());
        if (r >= 0 && r < tableSV.getRowCount()) {
            tableSV.setRowSelectionInterval(r, r);
        } else {
            tableSV.clearSelection();
        }

        int rowindex = tableSV.getSelectedRow();
        if (rowindex < 0)
            return;
        if (evt.isPopupTrigger() && evt.getComponent() instanceof JTable ) {
            JPopupMenu popup=new JPopupMenu() ;
            popup.show(evt.getComponent(), evt.getX(), evt.getY());
           
        }
    
    }//GEN-LAST:event_tableSVMouseReleased
    private void jComboBoxSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSubjectActionPerformed
        // TODO add your handling code here:
//        StudentManagerController studentManagerController=StudentManagerController.getInstance();
//        for(Department department:studentManagerController.getAllList())
//        {
//            System.out.println(department.getName());
//            jComboBoxDepartment.addItem(department.getName());
//        }
        
            
    }//GEN-LAST:event_jComboBoxSubjectActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         if(column.isEmpty())
        addColumn();
      
         //DefaultTableModel tablemodel = (DefaultTableModel) tableSV.getModel();
    Department department=studentManagerController.getAllList().get(jComboBoxDepartment.getSelectedIndex()) ;
    for(Student student: studentManagerController.getAllStudents(department))
    {
      //  "CT0402000", "CT", "Thieu", 0, "Ha Noi", "CT4B", new Date());
        Vector<Object> vector=new Vector<>();
        vector.add(student.getCode());
         // vector.add(student.getDepartmentCode());
          vector.add(student.getName());
           vector.add(student.getGender());
            vector.add(student.getAddress());
             vector.add(student.getKlass());
                          vector.add(student.getBirthday());
               
             data.add(vector);
    }
    
      tableSV.setModel(new DefaultTableModel(data,column)); 
     
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentManagementForm().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bNew;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBoxDepartment;
    private javax.swing.JComboBox<String> jComboBoxSubject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenuItem menuQuit;
    private javax.swing.JTable tableSV;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
